{{- if .Values.fs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "ks.labels" (merge (dict "service" .Values.fs.appKubernetesIoService) $) | nindent 4 }}
  name: fs
spec:
  replicas: {{ $.Values.fs.replicas }}
  selector:
    matchLabels:
      {{- include "ks.selectorLabels" (merge (dict "service" .Values.fs.appKubernetesIoService) $) | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "ks.labels" (merge (dict "service" .Values.fs.appKubernetesIoService) $) | nindent 8 }}
    spec:
      volumes:
        - name: {{ .Values.fs.volume_name }}
          persistentVolumeClaim:
            claimName: {{ .Values.fs.volume_claim_name }}
      initContainers:
        - name: init-config-server
          image: busybox
          command: ['sh', '-c', 'until nc -z config:8501; do echo waiting for config server; sleep 2; done;']
      containers:
        - name: {{ .Values.fs.appKubernetesIoService }}
          image: {{ .Values.fs.image }}
          volumeMounts:
            - mountPath: "{{ .Values.fs.mount_path }}"
              name: {{ .Values.fs.volume_name }}
          env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio_access_key
          - name: MINIO_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio_secret_key
          resources:
            limits:
              memory: {{ .Values.fs.resources.limits.memory }}
              cpu: {{ .Values.fs.resources.limits.cpu }}
            requests:
              cpu: {{ .Values.fs.resources.requests.cpu }}
              memory: {{ .Values.fs.resources.requests.memory }}          
          ports:
            - containerPort: {{ .Values.fs.targetPort }}
          command:
          - /bin/sh
          - -c
          - |
            minio server /data --console-address :9001
      {{- if and $.Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: Always
{{- end }}