apiVersion: v1
kind: Secret
metadata: 
  name: minio-secret
  labels:
    {{ include "ks.labels" $ | nindent 4 }}
type: Opaque
data: 
    minio_access_key: {{ .Values.fs.minio_access_key | b64enc | quote }}
    minio_secret_key: {{ .Values.fs.minio_secret_key | b64enc | quote }}